name: "Sign"

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 上班卡
    - cron: "10 03 * * *" # 每日签到检查，如不需要可删除这行
    - cron: "30 03 * * *" # 每日签到检查，如不需要可删除这行
    - cron: "0 10 * * *" # 下班卡
    - cron: "10 15 * * *" # 每日签到检查，如不需要可删除这行
    - cron: "30 15 * * *" # 每日签到检查，如不需要可删除这行

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install pytz
      run: |
        pip install pytz
      
    - name: Install Crypto
      run: |
        pip install pycryptodome
    
    - name: Start sign
      env:
        USERS: ${{ secrets.USERS }}
      run: |
        python main.py
